[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"

restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.env]]
name = "PORT"
value = "8080"


